
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: "Bluebuff | Cheap MLBB Diamonds & Game Topup In India",
        template: "%s | Bluebuff",
    },
    description:
        "Instant MLBB topup and cheap gaming credits in India. Bluebuff is the most affordable and secure platform for BGMI UC, Honor of Kings, and MLBB diamonds via UID.",
    keywords: [
        "mlbb recharge india cheap",
        "mlbb top up india instant",
        "buy ml diamonds india low price",
        "mlbb recharge with upi",
        "cheapest mlbb recharge website",
        "mlbb recharge trusted site india",
        "mlbb diamonds instant delivery india",
        "mobile legends recharge india fast",
        "mlbb top up india no login",
        "mlbb recharge website india cheap",
        "mlbb topup",
        "mlbb diamond topup",
        "mlbb diamond recharge",
        "buy mlbb diamonds",
        "mobile legends topup",
        "mlbb diamonds india",
        "mlbb recharge under 50 rs",
        "mlbb recharge under 80 rs india",
        "mlbb recharge under 100 rs india",
        "cheap mlbb diamonds 2024 india",
        "lowest price mlbb diamonds india",
        "mlbb diamond price list india",
        "mlbb recharge best price india",
        "mlbb diamond rate india today",
        "mlbb topup discount india",
        "mlbb recharge offer india today",
        "buy 86 diamonds mlbb india",
        "buy 172 diamonds mlbb india",
        "mlbb weekly pass recharge india",
        "mlbb twilight pass recharge india",
        "mlbb small diamond pack india",
        "mlbb mini pack recharge instant",
        "mlbb weekly pass cheapest india",
        "mlbb diamond bundle recharge india",
        "mlbb subscription recharge india",
        "mlbb starlight recharge india",
        "mlbb recharge by id server india",
        "mlbb topup uid only india",
        "instant mlbb recharge without login",
        "mlbb auto topup website india",
        "mlbb instant diamonds delivery",
        "fastest mlbb recharge india",
        "mlbb recharge in seconds india",
        "mlbb topup instant payment india",
        "mlbb recharge direct account india",
        "legit mlbb recharge india",
        "trusted mlbb diamond seller india",
        "safe mlbb topup site india",
        "real mlbb recharge website india",
        "genuine mlbb diamond store india",
        "secure mlbb recharge with upi",
        "best site to buy mlbb diamonds india",
        "how to buy mlbb diamonds with upi",
        "mlbb recharge guide india",
        "mlbb diamond recharge steps",
        "mobile legends payment methods india",
        "how instant mlbb topup works",
        "mlbb weekly pass worth it india",
        "mlbb cheapest recharge method india",
        "mlbb topup without moonton login",
        "mlbb recharge india paytm",
        "mlbb top up india phonepe",
        "mlbb diamonds google pay india",
        "bluebuff",
        "bluebuff topup",
        "bluebuff mlbb diamonds",
        "game topup india",
        "bgmi uc topup",
        "buy bgmi uc india",
        "hok tokens topup",
        "honor of kings topup india",
        "genshin impact topup india",
        "buy genesis crystals cheap",
        "magic chess topup india",
        "where winds meet recharge",
        "wuthering waves topup buy lunites",
        "wuthering waves recharge india"
    ],
    metadataBase: new URL("https://bluebuff.in"),
    openGraph: {
        title: "Bluebuff | Buy MLBB Diamonds Instantly",
        description:
            "Instant MLBB diamond top-up in India. Secure payments, fast delivery, and best prices at Bluebuff.",
        url: "https://bluebuff.in",
        siteName: "Bluebuff",
        type: "website",
    },
    robots: {
        index: true,
        follow: true,
    },
};
