// app/page.tsx
import HomeSection from "@/components/Home/Home";
import WhatsAppQRPopup from "@/components/WhatsAppQRPopup";

export const metadata = {
  title: "Bluebuff - Buy MLBB Diamonds Instantly in India | Best Game Topup Platform",
  description:
    "Bluebuff is India's most trusted gaming top-up platform. Buy Mobile Legends (MLBB) diamonds, BGMI UC, and other game credits instantly with fast delivery, secure payments, and the best prices.",
  keywords: [
    "mlbb recharge india cheap",
    "mlbb top up india instant",
    "buy ml diamonds india low price",
    "mlbb recharge with upi",
    "cheapest mlbb recharge website",
    "mlbb recharge trusted site india",
    "mlbb diamonds instant delivery india",
    "mobile legends recharge india fast",
    "mlbb top up india no login",
    "mlbb recharge website india cheap",
    "mlbb topup",
    "mlbb diamond topup",
    "mlbb diamond recharge",
    "buy mlbb diamonds",
    "mobile legends topup",
    "mlbb diamonds india",
    "mlbb recharge under 50 rs",
    "mlbb recharge under 80 rs india",
    "mlbb recharge under 100 rs india",
    "cheap mlbb diamonds 2024 india",
    "lowest price mlbb diamonds india",
    "mlbb diamond price list india",
    "mlbb recharge best price india",
    "mlbb diamond rate india today",
    "mlbb topup discount india",
    "mlbb recharge offer india today",
    "buy 86 diamonds mlbb india",
    "buy 172 diamonds mlbb india",
    "mlbb weekly pass recharge india",
    "mlbb twilight pass recharge india",
    "mlbb small diamond pack india",
    "mlbb mini pack recharge instant",
    "mlbb weekly pass cheapest india",
    "mlbb diamond bundle recharge india",
    "mlbb subscription recharge india",
    "mlbb starlight recharge india",
    "mlbb recharge by id server india",
    "mlbb topup uid only india",
    "instant mlbb recharge without login",
    "mlbb auto topup website india",
    "mlbb instant diamonds delivery",
    "fastest mlbb recharge india",
    "mlbb recharge in seconds india",
    "mlbb topup instant payment india",
    "mlbb recharge direct account india",
    "legit mlbb recharge india",
    "trusted mlbb diamond seller india",
    "safe mlbb topup site india",
    "real mlbb recharge website india",
    "genuine mlbb diamond store india",
    "secure mlbb recharge with upi",
    "best site to buy mlbb diamonds india",
    "how to buy mlbb diamonds with upi",
    "mlbb recharge guide india",
    "mlbb diamond recharge steps",
    "mobile legends payment methods india",
    "how instant mlbb topup works",
    "mlbb weekly pass worth it india",
    "mlbb cheapest recharge method india",
    "mlbb topup without moonton login",
    "mlbb recharge india paytm",
    "mlbb top up india phonepe",
    "mlbb diamonds google pay india",
    "bluebuff",
    "bluebuff topup",
    "bluebuff mlbb diamonds",
    "game topup india",
    "bgmi uc topup",
    "buy bgmi uc india",
    "hok topup india",
    "honor of kings topup",
    "buy hok tokens india cheap",
    "genshin impact topup india",
    "buy genesis crystals india",
    "genshin impact recharge cheap",
    "magic chess topup",
    "magic chess bang bang recharge",
    "where winds meet topup india",
    "where winds meet game recharge",
    "wuthering waves topup india",
    "wuthering waves recharge cheap",
    "buy lunites wuthering waves india"
  ],
  alternates: {
    canonical: "https://bluebuff.in/",
  },
  openGraph: {
    title: "Bluebuff - Buy MLBB Diamonds & Game Topups in India",
    description: "Instant gaming top-ups for MLBB, BGMI, and more in India. Secure payments, instant delivery at Bluebuff.",
    url: "https://bluebuff.in",
    siteName: "Bluebuff",
    images: [
      {
        url: "/logoBB.png",
        width: 1200,
        height: 630,
        alt: "Bluebuff - Gaming Topup India",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Bluebuff - Buy MLBB Diamonds Instantly in India",
    description: "Instant gaming top-ups for MLBB, BGMI, and more in India. Secure payments, instant delivery at Bluebuff.",
    images: ["/logoBB.png"],
  },
  verification: {
    google: "QWK_nNCNa9UOVWVpaOf5Ux5GkTuUKhRZndHGDNfMoj8",
  },
};

export default function Page() {
  return (
    <main>
      <WhatsAppQRPopup />

      <HomeSection />
    </main>
  );
}
